import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Head } from 'next/document';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className='light'>
      <head>
        <title>Portal IAW</title>
      </head>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>

  );
}
