// Generated by https://quicktype.io

import { IColumn } from "./ILibros";

export interface ICategoria {
    cod:          string;
    name:        string;
    descripcion: string;
    logo:        string;
}

const ColumCategoria:IColumn[] = [
    {
      key: "name",
      label: "Nombre",
    },
    {
      key: "descripcion",
      label: "Titulo",
    },
    {
      key: "logo",
      label: "Imagen",
    }
  ];

  export default ColumCategoria;